In [2]:
import os
print(os.curdir)

.

In [3]:
import pandas as pd

In [4]:
customers_df = pd.read_csv("../data/raw/olist_customers_dataset.csv")
geolocation_df = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
order_items_df = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
order_payments_df= pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
order_reviews_df = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
orders_df =pd.read_csv("../data/raw/olist_orders_dataset.csv")
products_df = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers_df = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
category_name_translation_df = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [5]:
print(customers_df.head(2))
print("--"*20)
print("\n"*3)
print(geolocation_df.head(2))
print("--"*20)
print("\n"*3)
print(order_items_df.head(2))
print("--"*20)
print("\n"*3)
print(order_payments_df.head(2))
print("--"*20)
print("\n"*3)
print(order_reviews_df.head(2))
print("--"*20)
print("\n"*3)
print(orders_df.head(2))
print("--"*20)
print("\n"*3)
print(products_df.head(2))
print("--"*20)
print("\n"*3)
print(products_df.head(2))
print("--"*20)
print("\n"*3)
print(sellers_df.head(2))
print("--"*20)
print("\n"*3)
print(category_name_translation_df.head(2))

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
----------------------------------------




   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
----------------------------------------




                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36

   shipping_limit_date  price  freight_value
0  2017-09-19 09:45:35   58.9          13.29
1  2017-05-03 11:05:13  239.9          19.93
----------------------------------------




                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
----------------------------------------




                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33

   review_score review_comment_title review_comment_message  \
0             4                  NaN                    NaN
1             5                  NaN                    NaN

  review_creation_date review_answer_timestamp
0  2018-01-18 00:00:00     2018-01-18 21:46:59
1  2018-03-10 00:00:00     2018-03-11 03:05:13
----------------------------------------




                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
----------------------------------------




                         product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                 artes

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
----------------------------------------




                         product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                 artes

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
----------------------------------------




                          seller_id  seller_zip_code_prefix seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                   13023    campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844  mogi guacu

  seller_state
0           SP
1           SP
----------------------------------------




    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

In [6]:
## Ttransforming customers_df
customers_df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [8]:
##understand the table
print(customers_df.info())
print("\n"*5)
print(customers_df.describe(include='all'))

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None






                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        customer_zip_code_prefix customer_city customer_state
count               99441.000000         99441          99441
unique                       NaN          4119             27
top                          NaN     sao paulo             SP
freq                         NaN         15540          41746
mean                35137.474583           NaN            NaN
std                 29797.938996           NaN            NaN
min                  1003.000000           NaN            NaN
25%                 11347.000000           NaN            NaN
50%                 24416.000000           NaN            NaN
75%                 58900.000000           NaN            NaN
max                 99990.000000           NaN            NaN

In [9]:
#checking duplicated
print(customers_df.duplicated().sum())
print(customers_df["customer_id"].duplicated().sum())

0
0

In [10]:
customers_df["customer_id"].is_unique

True

In [11]:
print(customers_df.columns)
print(type(customers_df.columns))

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')
<class 'pandas.Index'>

In [12]:
customers_df.select_dtypes(include=["number"]).columns.to_list()
# here select_dtypes will return a dataframe where column's elements
# either integer or float

['customer_zip_code_prefix']

In [13]:
numerical_features= [each for each in customers_df.columns if customers_df[each].dtype != "str"]
categorical_features = [each for each in customers_df.columns if customers_df[each].dtype=="str"]

In [14]:
print(numerical_features)
print(categorical_features)

['customer_zip_code_prefix']
['customer_id', 'customer_unique_id', 'customer_city', 'customer_state']

In [15]:
print(customers_df['customer_unique_id'].value_counts())
print(customers_df.customer_id.value_counts())
"""| Column               | Meaning                                             |
| -------------------- | --------------------------------------------------- |
| `customer_id`        | **Unique identifier for each order/account record** |
| `customer_unique_id` | **Unique identifier for the real customer**         |
"""

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
                                    ..
1a29b476fee25c95fbafc67c5ac95cf8     1
d52a67c98be1cf6a5c84435bd38d095d     1
e9f50caf99f032f0bf3c55141f019d99     1
73c2643a0a458b49f58cea58833b192e     1
84732c5050c01db9b23e19ba39899398     1
Name: count, Length: 96096, dtype: int64
customer_id
06b8999e2fba1a1fbc88172c00ba8bc7    1
18955e83d337fd6b2def6b18a428ac77    1
4e7b3e00288586ebd08712fdd0374a03    1
b2b6027bc5c5109e529d4dc6358b12c3    1
4f2d8ab171c80ec8364f7c12e35b23ad    1
                                   ..
17ddf5dd5d51696bb3d7c6291687be6f    1
e7b71a9017aa05c9a7fd292d714858e8    1
5e28dfe12db7fb50a4b2f691faecea5e    1
56b18e2166679b8a959d72dd06da27f9    1
274fa6071e5e17fe303b9748641082c8    1
Name: count, Length: 99441, dtype: int64

'| Column               | Meaning                                             |\n| -------------------- | --------------------------------------------------- |\n| `customer_id`        | **Unique identifier for each order/account record** |\n| `customer_unique_id` | **Unique identifier for the real customer**         |\n'

In [16]:
for each in categorical_features:
    customers_df[each]=customers_df[each].str.strip()
    customers_df[each]=customers_df[each].str.replace(r"\s{2,}", " ", regex=True)

In [17]:
print(customers_df.customer_state.value_counts())

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [18]:
customers_df.head(50)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG
11,5aa9e4fdd4dfd20959cad2d772509598,2a46fb94aef5cbeeb850418118cee090,20231,rio de janeiro,RJ
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS
15,206f3129c0e4d7d0b9550426023f0a08,21f748a16f4e1688a9014eb3ee6fa325,13412,piracicaba,SP
16,a7c125a0a07b75146167b7f04a7f8e98,5c2991dbd08bbf3cf410713c4de5a0b5,22750,rio de janeiro,RJ
17,c5c61596a3b6bd0cee5766992c48a9a1,b6e99561fe6f34a55b0b7da92f8ed775,7124,guarulhos,SP
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP
19,49d0ea0986edde72da777f15456a0ee0,3e6fd6b2f0d499456a6a6820a40f2d79,68485,pacaja,PA
20,154c4ded6991bdfa3cd249d11abf4130,e607ede0e63436308660236f5a52da5e,88034,florianopolis,SC
21,690172ab319622688d3b4df42f676898,a96d5cfa0d3181817e2b946f921ea021,74914,aparecida de goiania,GO
22,2938121a40a20953c43caa8c98787fcb,482441ea6a06b1f72fe9784756c0ea75,5713,sao paulo,SP
23,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR
24,cb721d7b4f271fd87011c4c83462c076,a5844ba4bfc8d0cc61d13027c7e63bcc,8225,sao paulo,SP
25,f681356046d9fde60e70c73a18d65ea2,5f102dd37243f152aec3607970aad100,9121,santo andre,SP
26,167bd30a409e3e4127df5a9408ebd394,9c0096673baf55453a50073f12d1a37f,74310,goiania,GO
27,6e359a57a91f84095cc64e1b351aef8c,2e6a42a9b5cbb0da62988694f18ee295,4571,sao paulo,SP
28,e0eea8f69a457b3f1fa246e44c9ebefd,4d221875624017bc47b4d1ce7314a5b7,29311,cachoeiro de itapemirim,ES
29,e3109970a3fe8021d5ff82c577ce5606,a8654e2af5da6bb72f52c22b164855e1,5528,sao paulo,SP
30,261cb4f92498ca05d5bd1a327a261d9c,424aca6872c5bab80780a8dec03b7516,12235,sao jose dos campos,SP
31,6f92779347724b67e44e3224f3b4cffd,bf4862777db128507e9efcc789215e9b,18130,sao roque,SP
32,2d5831cb2dff7cdefba62e950ae3dc7b,e9dd12dca17352644a959d9dea133935,42800,camacari,BA
33,b2bed119388167a954382cca36c4777f,e079b18794454de9d2be5c12b4392294,27525,resende,RJ
34,469634941c27cd844170935a3cf60b95,ef07ba9aa5226f77264ffa5762b2280b,81750,curitiba,PR
35,df0aa5b8586495e0ddf6b601122e43a1,85d234692f7bee8d6fea586e237334b6,13175,sumare,SP
36,41c8f4b570869791379a925899a6af8a,fe3634ccefbcdb0537b45fd589e32e8e,7170,guarulhos,SP
37,54f755c3fd2709231f9964a1430c5218,40febde16f4718a5def537786473b0be,93415,novo hamburgo,RS
38,4c06b42fbf7b97ab10779cda5549cd1c,07d190f123147d9e89d4b922543d7948,65075,sao luis,MA
39,b6368ca0f56d4632f44d58ca431487b2,dd992305cba295d997f263dbdf4e8c2e,88104,sao jose,SC
40,4a0e66fd30684aa1409cd1b66fec77cc,86085586aaa8c5f47ed0b400da64c59d,7176,guarulhos,SP
41,c168abb9077b7821adae01dc1f0886c5,5ad58a4e6a1a656b6bed070cadbaa003,35960,santa barbara,MG
42,a3b0fda37bae14cf754877bed475e80c,c9158d089637ab443c78984d20da7fc0,5727,sao paulo,SP
43,0ccd415657ae8a6cd1c71b00155a019e,66cc90195ca44cc7ac6a1cd0e1e1e7b2,7053,guarulhos,SP
44,c532a74a3ebf1bacce2e2bcce3783317,91ec50a00ae74d0a229d2efdf4344e1e,14026,ribeirao preto,SP
45,19cecb194f54e614b70d971306a9931b,d251c190ca75786e9ab937982d60d1d4,30320,belo horizonte,MG
46,f34a6e874087ec1f0e3dab9fdf659c5d,233896de79986082f1f479f1f85281cb,38300,ituiutaba,MG
47,c132855c926907970dcf6f2bf0b33a24,a8ae36a2bb6c2bbc3b5d62ede131c9ef,18740,taquarituba,SP
48,df85b96ba2ce3e49bde101b1614f52ac,8d46223c91cbeb93e0930ca8bd8ffca2,83085,sao jose dos pinhais,PR
49,4d27341acd30a36bca39008ee9bb9050,e021e698833bdeb89dfef3acb2e91f37,89254,jaragua do sul,SC

In [19]:
customers_df["customer_city"].unique()

<StringArray>
[               'franca', 'sao bernardo do campo',             'sao paulo',
       'mogi das cruzes',              'campinas',        'jaragua do sul',
               'timoteo',              'curitiba',        'belo horizonte',
         'montes claros',
 ...
              'balbinos',          'serra bonita',          'venda branca',
           'sanga puita',               'queiroz',                'siriji',
   'natividade da serra',          'monte bonito',            'sao rafael',
     'eugenio de castro']
Length: 4119, dtype: str

In [20]:
customers_df[customers_df["customer_city"].str.contains("sao", case=False, na=False)]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP
...,...,...,...,...,...
99415,184e0c2cfc746789643521df0e9ff904,c64ede6d0ae8901b1b6fb03528c1b7e6,68660,sao miguel do guama,PA
99422,821a7275a08f32975caceff2e08ea262,046470763123d3d6364f89095b4e47ab,5734,sao paulo,SP
99423,c6ece8a5137f3c9c3a3a12302a19a2ac,aaf22868003377e859049dcf5f0b3fdf,1323,sao paulo,SP
99426,935993f47af1ed7d0715c26b686341c5,4452b8ef472646c4cc042cb31a291f3b,12236,sao jose dos campos,SP
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP

In [21]:
customers_df[customers_df['customer_zip_code_prefix']== 1151]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
17280,8d401266c416fe74129569742199d75f,632b9f83894a36849b293ce84d62d399,1151,sao paulo,SP
27142,4eb9eccb3b24a747f725dbee821a88b7,15f755c9f45213070f1b781ed78ea55c,1151,sao paulo,SP
48774,3532ba38a3fd242259a514ac2b6ae6b6,4fa4365000c7090fcb8cad5713c6d3db,1151,sao paulo,SP
54656,dc6c74aedc9324030804b25fa1021b17,6be824f2933ae5094244f962068ca531,1151,sao paulo,SP
67534,8c55956d70fca64193668429b9f8d8ce,61a7c7a2d1ee1715b63e0d22a1129fc5,1151,sao paulo,SP
81540,e9490b645b17d03cfde928d84d38a916,b00fa88d0838e8f9ecc8c34356655c4e,1151,sao paulo,SP
82361,188ac4e8b7765d24cdb434112a99111f,27a42ae2a62b4442dd98ec2e16193118,1151,sao paulo,SP
91845,020fff139f1af3a6dff28456f386fe2d,00705dcbc0b9cad67abd658612770905,1151,sao paulo,SP

In [22]:
pd.set_option("display.max_seq_items", None)
print(customers_df.customer_city.unique())

<StringArray>
[                          'franca',            'sao bernardo do campo',
                        'sao paulo',                  'mogi das cruzes',
                         'campinas',                   'jaragua do sul',
                          'timoteo',                         'curitiba',
                   'belo horizonte',                    'montes claros',
                   'rio de janeiro',                 'lencois paulista',
                    'caxias do sul',                       'piracicaba',
                        'guarulhos',                           'pacaja',
                    'florianopolis',             'aparecida de goiania',
                      'santo andre',                          'goiania',
          'cachoeiro de itapemirim',              'sao jose dos campos',
                        'sao roque',                         'camacari',
                          'resende',                           'sumare',
                    'novo hamburgo',                         'sao luis',
                         'sao jose',                    'santa barbara',
                   'ribeirao preto',                        'ituiutaba',
                      'taquarituba',             'sao jose dos pinhais',
                         'barrinha',                           'parati',
                         'dourados',                         'trindade',
                         'cascavel',                        'fortaleza',
                         'brasilia',                          'pelotas',
                     'porto alegre',                            'salto',
                          'jundiai',                         'cacapava',
                      'sao vicente',                       'uberlandia',
                         'botelhos',                      'sao goncalo',
                        'araucaria',                      'nova iguacu',
                     'areia branca',            'campos dos goytacazes',
                       'sao carlos',                          'itajuba',
                   'cruz das almas',                        'vassouras',
                 'feira de santana',                          'niteroi',
                           'sobral',                      'divinopolis',
                   'paraiba do sul',                         'paulista',
                      'carapicuiba',                    'bom principio',
                    'astolfo dutra',                         'marialva',
            'sao jose do rio preto',                        'cabo frio',
                         'contagem',                          'cafeara',
             'sao joaquim da barra',                    'foz do iguacu',
                           'suzano',                            'timbo',
                         'camboriu',                     'nova bassano',
                       'rio grande',                'braganca paulista',
                  'barra do garcas',                             'embu',
                        'urussanga',                    'silvianopolis',
                       'gameleiras',                            'belem',
                  'pocos de caldas',                           'santos',
                         'piracaia',                            'sinop',
                          'guaruja',                          'barueri',
                            'feliz',                         'jambeiro',
                         'ipatinga',                             'tupa',
                         'blumenau',                          'moncoes',
               'balneario camboriu',                    'vargem grande',
                    'rio brilhante',                      'eugenopolis',
                         'paulinia',                        'apucarana',
                           'recife',                           'osasco',
                         'valinhos',                           'manaus',
                         'cidreira',                         'santiago',
                         'sao sepe',                    'alta floresta',
          'jaboatao dos guararapes',                          'ibatiba',
                      'hortolandia',                            'cotia',
                            'macae',                         'saudades',
                           'macapa',                'salto de pirapora',
                  'taboao da serra',                        'bom jesus',
          'santa cruz do rio pardo',                          'diadema',
                       'santa ines',                         'serrinha',
                       'votorantim',                         'itatiaia',
                  'duque de caxias',                        'varre-sai',
                       'vila velha',                      'mangaratiba',
                          'atibaia',                         'salvador',
                           'maceio',                          'birigui',
                       'petropolis',                        'sao pedro',
                      'jaguariaiva',                  'franco da rocha',
                  'pindamonhangaba',                            'irati',
                          'ribeira',                        'barbacena',
                         'limoeiro',                 'espigao do oeste',
                     'belford roxo',               'coronel fabriciano',
                         'itanhaem',                        'bebedouro',
                        'americana',                              'uba',
                        'arapongas',                          'vinhedo',
                           'itajai',                            'bauru',
                       'pradopolis',                         'aripuana',
                       'guaratinga',                       'ponta pora',
                        'aracatuba',                    'volta redonda',
                          'maringa',                       'araraquara',
                           'matipo',        'santo antonio da patrulha',
                      'barra mansa',                       'diamantina',
                        'mairinque',         'capitao leonidas marques',
         'sao sebastiao do paraiso',                   'rosario do sul',
                          'itaguai',                        'paraopeba',
                       'guarapuava',                        'crisolita',
                            'pirai',                         'linhares',
                           'agudos',               'sao joao de meriti',
                       'navegantes',                     'pirassununga',
               'faxinal dos guedes',                         'criciuma',
                     'nova venecia',                      'passo fundo',
                             'ibia',                         'manhuacu',
                         'altamira',                          'aperibe',
                           'cuiaba',                           'canoas',
                          'cubatao',             'campo limpo paulista',
                            'cambe',                  'itaquaquecetuba',
               'sao caetano do sul',        'sao goncalo do rio abaixo',
                         'rolandia',                    'tres coracoes',
                  'cacapava do sul',              'sao joao nepomuceno',
                             'leme',                           'araras',
                           'cortes',                          'brusque',
                       'montenegro',                         'itaberai',
            'santa rosa de viterbo',               'agua fria de goias',
                            'marau',                          'curvelo',
                     'juiz de fora',                       'mogi-guacu',
                    'guaratingueta',                        'paranagua',
                             'lins',                        'campo bom',
                      'sertaozinho',                      'tres lagoas',
                              'jau',                  'campos de julio',
                        'saquarema',                   'artur nogueira',
                             'uaua',                          'jandira',
                        'concordia',                    'nova friburgo',
                         'sorocaba',                       'ponte nova',
                         'araquari',                           'muriae',
                        'nova lima',                          'inhumas',
                           'italva',                        'tres rios',
                      'santa maria',                          'itagiba',
                         'paracatu',                            'xaxim',
               'laranjeiras do sul',                         'itapiuna',
                          'formosa',                            'ivoti',
                         'juazeiro',                     'ponta grossa',
                   'campina grande',                             'maua',
                        'salgueiro',                           'lorena',
                           'toledo',              'sao pedro da aldeia',
                       'vianopolis',                        'arapiraca',
                     'porto seguro',                        'ariquemes',
               'presidente getulio',                        'rio negro',
                   'ribeirao pires',         'sao jose da coroa grande',
               'agua doce do norte',                         'anapolis',
                       'guararapes',                      'farroupilha',
                         'almenara',                   'rio das ostras',
                         'gravatai',                          'brumado',
                          'marilia',                          'itabira',
                          'claudia',                    'para de minas',
                     'miguelopolis',                       'terra roxa',
                         'araguari',                            'lages',
                   'embu das artes',                          'limeira',
                          'taubate',                  'santa fe do sul',
                         'caieiras',                        'carangola',
                 'chapada do norte',                           'loanda',
                       'passa tres',               'aracoiaba da serra',
                         'itaborai',                          'vitoria',
                 'sao bento do sul',                       'indaiatuba',
                          'boituva',                      'teresopolis',
                      'pinhalzinho',                        'petrolina',
                            'natal',                        'barreiras',
                         'januaria',                          'ipiabas',
                     'firminopolis',                        'joinville',
                           'mococa',                          'valenca',
              'sao miguel do oeste',                            'jales',
                      'rio formoso',                   'angra dos reis',
                   'alfredo chaves',                       'itapetinga',
                           'gurupi',         'nucleo residencial pilar',
                       'coromandel',                       'charqueada',
                    'itau de minas',                          'ibiruba',
                         'bertioga',                            'ipiau',
                       'matozinhos',                         'teresina',
                       'entre rios',                            'juina',
                        'mairipora',          'marechal candido rondon',
                            'avare',                             'icem',
                    'sao sebastiao',                            'serra',
                         'mirassol',                        'taperuaba',
                          'alfenas',                       'leopoldina',
            'sao joao da boa vista',                       'parnamirim',
              'teixeira de freitas',                      'joao pessoa',
                          'chacara',                  'rio novo do sul',
                          'guapore',                       'rio branco',
            'ferraz de vasconcelos',                      'petrolandia',
                          'araruna',                          'gravata',
                           'alegre',                         'londrina',
                 'senhor do bonfim',              'santana de parnaiba',
                      'piratininga',                    'monte carmelo',
                         'ipiranga',                          'jacarei',
                            'picos',                              'una',
                           'taguai',                          'peabiru',
                        'conquista',                            'bicas',
                        'forquilha',                         'guaicara',
                    'santa vitoria',                       'adamantina',
                        'rio claro',                  'sao jose de uba',
                          'sorriso',                          'aracaju',
             'conselheiro lafaiete',                       'taguatinga',
                          'tiangua',                        'paranaiba',
                  'david canabarro',                          'itarare',
                         'cajueiro',                         'cruzeiro',
                'santa cruz do sul',              'presidente epitacio',
                        'castanhal',                        'cariacica',
            'bom jesus dos perdoes',                      'urucurituba',
                           'olinda',            'sao jose do rio pardo',
                       'guapimirim',           'vargem grande paulista',
                          'chapeco',                          'videira',
                           'canapi',                 'pontal do parana',
                  'bento goncalves',                          'caceres',
                         'bituruna',             'sao bento do sapucai',
                             'mage',                     'forquilhinha',
                        'itaberaba',                          'gramado',
                           'guacui',                      'pato branco',
                          'itanhem',                           'palmas',
                             'bage',                 'francisco morato',
                       'cosmopolis',                            'carmo',
               'armacao dos buzios',           'santa maria da vitoria',
                   'pedro leopoldo',                      'tres marias',
           'santo antonio de padua',                      'porto feliz',
                           'gaspar',                          'palhoca',
                     'pouso alegre',                          'guaiuba',
                        'fraiburgo',                            'aurea',
                         'botucatu',                          'corumba',
                          'cajamar',                        'queimados',
                'sao jorge do ivai',                 'nova laranjeiras',
                          'guaxupe',                     'osvaldo cruz',
                            'ivora',                     'anaurilandia',
                    'caraguatatuba',                      'regeneracao',
                            'bilac',                          'faxinal',
                      'pedro velho',                          'uberaba',
                           'viamao',               'cachoeira de minas',
                      'coelho neto',                          'itajobi',
               'carmo do rio claro',                           'marica',
            'campo novo do parecis',                        'boa vista',
                          'ipameri',                   'carlos barbosa',
                          'anicuns',                      'rio bananal',
             'lavras da mangabeira',                          'balsamo',
                          'guariba',                    'sao vendelino',
                     'campo mourao',                          'aracati',
      'santo antonio do descoberto',        'santo amaro da imperatriz',
                            'betim',                           'vicosa',
                       'dom eliseu',                      'campo largo',
               'santa rosa de lima',                         'quissama',
                     'mirandopolis',                          'itapevi',
                'francisco beltrao',                     'dias d'avila',
                   'novo horizonte',                              'poa',
                        'querencia',                     'campo grande',
                         'pedreira',                    'pariquera-acu',
                     'itabaianinha',                         'pitangui',
                         'araruama',                    'campo formoso',
                         'guanambi',                         'itapolis',
                      'pederneiras',                        'itabirito',
                         'itaipava',                    'arroio do sal',
                           'glaura',                   'lagoa vermelha',
                          'mantena',                          'peruibe',
                          'tubarao',                           'bonfim',
                         'alvorada',                       'patrocinio',
                         'mineiros',                          'itabuna',
                          'tijucas',           'santo antonio de jesus',
                         'canarana',             'itapecerica da serra',
             'nova prata do iguacu',                     'treze tilias',
                         'anchieta',                         'quatigua',
                          'iturama',                     'tres de maio',
       'santa rita do passa quatro',                 'porto esperidiao',
                  'bonfim paulista',                           'cajuru',
                          'cacador',                      'paragominas',
             'boa esperanca do sul',                      'tres pontas',
                'juazeiro do norte',                           'bambui',
        'comendador levy gasparian',             'sao miguel do aleixo',
              'palmeira dos indios',                        'cerquilho',
                'saudade do iguacu',                          'ipaussu',
            'alto paraiso de goias',                     'santa isabel',
                     'quirinopolis',                          'caruaru',
                'casimiro de abreu',                        'chavantes',
                       'ecoporanga',               'cachoeira paulista',
                        'rio verde',                        'maracanau',
                        'canoinhas',                        'ituverava',
                 'buriti dos lopes',                   'rio do antonio',
                         'guaranta',                      'santa luzia',
                          'tucurui',                        'paranavai',
                          'pinhais',             'governador valadares',
                'trajano de moraes',                            'caete',
                       'abaetetuba',                           'lavras',
                  'coronel joao sa',                           'divino',
                         'macaubas',                          'lucelia',
           'brejo da madre de deus',                            'carai',
                         'corbelia',                         'varginha',
                       'ouro preto',                            'prado',

In [23]:
customers_df["customer_city"]=customers_df.customer_city.str.lower()

In [24]:
geolocation_df.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [25]:
geolocation_df.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [26]:
import numpy as np

In [27]:
geolocation_df.iloc[np.where(geolocation_df.geolocation_state=="SP")[0]]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
404265,19970,-22.779062,-50.218287,palmital,SP
404266,19905,-22.997601,-49.885928,ourinhos,SP
404267,19907,-22.978498,-49.875919,ourinhos,SP
404268,19905,-22.993127,-49.887665,ourinhos,SP
404269,19911,-22.972685,-49.864647,ourinhos,SP

In [28]:
print(geolocation_df.info())
print(geolocation_df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
None
       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [29]:
import numpy as np
print(type(np.where(geolocation_df["geolocation_zip_code_prefix"]<0)))

<class 'tuple'>

In [30]:
import numpy as np
geolocation_df.iloc[np.where(geolocation_df["geolocation_zip_code_prefix"]<0)[0]]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [31]:
geolocation_df.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [32]:
numerical_features = geolocation_df.select_dtypes(include="number").columns.to_list()
categorical_features = geolocation_df.select_dtypes(include="str").columns.to_list()
print(categorical_features)
print(numerical_features)

['geolocation_city', 'geolocation_state']
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng']

In [33]:
geolocation_df.geolocation_city.unique()

<StringArray>
[                             'sao paulo',
                              'são paulo',
                  'sao bernardo do campo',
                                'jundiaí',
                        'taboão da serra',
                               'sãopaulo',
                                     'sp',
                             'sa£o paulo',
                    'sao jose dos campos',
                                 'osasco',
                            'carapicuíba',
                            'carapicuiba',
                                'barueri',
                    'santana de parnaiba',
                  'pirapora do bom jesus',
                    'santana de parnaíba',
                                'jandira',
                                'itapevi',
                                  'cotia',
                        'taboao da serra',
                 'vargem grande paulista',
                         'embu das artes',
                   'itapecerica da serra',
                                   'embu',
                  'são lourenço da serra',
                  'sao lourenco da serra',
                             'embu-guacu',
                             'embu-guaçu',
                             'embu guaçu',
                              'juquitiba',
                             'embu guacu',
                              'embuguacu',
                              'guarulhos',
                             'adamantina',
                           'guarulhos-sp',
                                  'aruja',
                                  'arujá',
                           'santa isabel',
                              'mairipora',
                              'mairiporã',
                                'cajamar',
                               'caieiras',
                             'jordanesia',
                               'polvilho',
                                   'mauá',
                             'jordanésia',
                        'franco da rocha',
                       'francisco morato',
                                    'poa',
                        'itaquaquecetuba',
                  'ferraz de vasconcelos',
                                    'poá',
                                 'suzano',
                        'mogi das cruzes',
                          'mogidascruzes',
                            'salesopolis',
                         'biritiba-mirim',
                              'guararema',
                            'salesópolis',
                         'biritiba mirim',
                            'santo andre',
                            'santo andré',
                                   'maua',
                         'ribeirão pires',
                         'ribeirao pires',
                    'rio grande da serra',
                     'sao caetano do sul',
                     'são caetano do sul',
                  'são bernardo do campo',
                                'sbcampo',
                                'diadema',
                                 'santos',
                               'bertioga',
                                'caruara',
                            'sao vicente',
                            'são vicente',
                                'guarujá',
                                'guaruja',
                                'cubatao',
                                'cubatão',
                          'sao sebastiao',
                                'ubatuba',
                               'ilhabela',
                          'caraguatatuba',
                          'são sebastião',
                               'maresias',
                 'sao francisco da praia',
                 'são francisco da praia',
                               'mongagua',
                           'praia grande',
                               'mongaguá',
                               'itanhaem',
                                'peruibe',
                                'itariri',
                        'pedro de toledo',
                               'itanhaém',
                                'peruíbe',
                               'ana dias',
                               'miracatu',
                                 'juquia',
                                 'juquiá',
                          'pariquera-acu',
                                 'cajati',
                               'registro',
                            'jacupiranga',
                          'ilha comprida',
                         'barra do turvo',
                               'eldorado',
                                 'iguape',
                               'cananéia',
                               'cananeia',
                            'sete barras',
                          'pariquera-açu',
                                'taubate',
                                'taubaté',
                    'natividade da serra',
                               'tremembe',
                               'lagoinha',
                               'tremembé',
                      'redencao da serra',
                               'catucaba',
                 'sao luiz do paraitinga',
                 'sao luis do paraitinga',
                 'são luiz do paraitinga',
                    'são josé dos campos',
                               'cacapava',
                              'paraibuna',
                               'caçapava',
                               'jambeiro',
                        'monteiro lobato',
                   'sao francisco xavier',
                   'são francisco xavier',
                                'jacarei',
                                'jacareí',
                           'santa branca',
                                'igarata',
                                'igaratá',
                        'pindamonhangaba',
                   'são bento do sapucaí',
                       'campos do jordao',
                   'sao bento do sapucai',
                'santo antonio do pinhal',
                       'campos do jordão',
                'santo antônio do pinhal',
                          'guaratingueta',
                                  'potim',
                          'guaratinguetá',
                              'aparecida',
                                  'cunha',
                                'roseira',
                        'campos de cunha',
                                 'lorena',
                     'cachoeira paulista',
                                'piquete',
                              'silveiras',
                                  'canas',
                               'cruzeiro',
                              'lavrinhas',
                                 'arapeí',
                                 'queluz',
                                 'arapei',
                                'bananal',
                   'sao jose do barreiro',
                   'são josé do barreiro',
                                 'areias',
                                'atibaia',
                      'braganca paulista',
                  'bom jesus dos perdoes',
                               'piracaia',
                  'bom jesus dos perdões',
                             'pedra bela',
                      'bragança paulista',
                             'joanopolis',
                                 'vargem',
                        'nazaré paulista',
                        'nazare paulista',
                             'joanópolis',
                            'pinhalzinho',
                                 'tuiuti',
                               'campinas',
                         'artur nogueira',
                            'hortolandia',
                               'paulinia',
                                 'sumare',
                             'cosmopolis',
                              'monte mor',
                            'hortolândia',
                                 'sumaré',
                             'cosmópolis',
                               'paulínia',
                      'engenheiro coelho',
                                'itatiba',
                                'vinhedo',
                                'jundiai',
                               'valinhos',
                        'varzea paulista',
                               'louveira',
                                 'jarinu',
                   'campo limpo paulista',
                              'morungaba',
                                'itupeva',
                        'várzea paulista',
                             'indaiatuba',
                               'capivari',
                                  'salto',
                                    'itu',
                            'nova odessa',
                               'cabreuva',
                           'elias fausto',
                                 'rafard',
                         'rio das pedras',
                                 'jacare',
                               'cabreúva',
                                'mombuca',
                                 'jacaré',
                      'jacaré (cabreúva)',
                                'cardeal',
                      'jacare (cabreuva)',
                   'bom fim do bom jesus',
                              'americana',
                                'limeira',
                             'piracicaba',
                  'santa bárbara d'oeste',
                  'santa barbara d'oeste',
                               'saltinho',
                          'cordeiropolis',
                           'iracemápolis',
                           'iracemapolis',
                  'santa barbara d oeste',
                          'cordeirópolis',
                   'santa bárbara doeste',
                   'santa barbara doeste',
                  'santa bárbara d`oeste',
                              'rio claro',
                             'sao carlos',
                                 'ipeuna',
                        'santa gertrudes',
                              'itirapina',
                             'charqueada',
                             'são carlos',
                        'ribeirao bonito',
                                 'ipeúna',
                              'sao pedro',
                              'são pedro',
                                'dourado',
                             'corumbataí',
                              'analandia',
                     'aguas de sao pedro',
                             'corumbatai',
                          'santa eudóxia',
                     'águas de são pedro',
                          'agua vermelha',
                        'ribeirão bonito',
                                 'araras',
                           'pirassununga',
                         'porto ferreira',
               'santa cruz das palmeiras',
             'santa rita do passa quatro',
                                   'leme',
                             'descalvado',
                'santa cruz da conceicao',
                'santa cruz da conceição',
                                 'mococa',
                  'são josé do rio pardo',
                  'sao jose do rio pardo',
                            'casa branca',
                                'caconde',
                                 'tambau',
                             'tapiratiba',
                           'divinolandia',
                'são benedito das areias',
                                  'itobi',
                 'sao sebastiao da grama',
                                 'tambaú',
                                 'igarai',
                 'são sebastião da grama',
                           'divinolândia',
                           'lagoa branca',
                'sao benedito das areias',
                           'venda branca',
                                 'igaraí',
                             'jaguariuna',
                   'vargem grande do sul',
                             'mogi-guacu',
                 'santo antonio de posse',
                             'mogi guaçu',
                 'santo antônio de posse',
                  'sao joao da boa vista',
                             'mogi mirim',
                             'jaguariúna',
                               'holambra',
                                  'aguai',
                                'conchal',
                             'mogi guacu',
                           'estiva gerbi',
                  'são joão da boa vista',
                             'mogi-mirim',
                         'aguas da prata',
                                  'aguaí',
                    'monte alegre do sul',
                         'águas da prata',
                  'martinho prado junior',
                   'sao roque da fartura',
                                 'amparo',
                                'itapira',
                                'socorro',
                                'lindoia',
                       'aguas de lindoia',
                               'pedreira',
                            'serra negra',
               'espirito santo do pinhal',
                       'águas de lindóia',
                 'barao ataliba nogueira',
               'espírito santo do pinhal',
                 'barão ataliba nogueira',
                'santo antonio do jardim',
                'santo antônio do jardim',
                                'lindóia',
                              'eleutério',
                              'eleuterio',
                         'ribeirao preto',
                         'ribeirão preto',
                            'sertãozinho',
                            'sertaozinho',
                                'serrana',
                                 'pontal',
                              'cravinhos',
                        'bonfim paulista',
                              'guatapará',
                                 'dumont',
                              'guatapara',
                                 'candia',
                                 'cajuru',
                           'luis antonio',
                              'sao simao',
                  'santa rosa de viterbo',
                             'serra azul',
                           'luís antônio',
                   'cassia dos coqueiros',
                              'são simão',
                'santa cruz da esperanca',
                   'cássia dos coqueiros',
               'santo antonio da alegria',
                              'brodowski',
                               'batatais',
                            'altinopolis',
                            'altinópolis',
               'santo antônio da alegria',
                                 'franca',
                              'jeriquara',
                                'rifaina',
                 'sao jose da bela vista',
                      'cristais paulista',
                    'patrocinio paulista',
                             'pedregulho',
                               'itirapuã',
                    'patrocínio paulista',
                               'itirapua',
                      'ribeirao corrente',
                               'restinga',
                 'são josé da bela vista',
                      'ribeirão corrente',
                              'franca sp',
                              'igarapava',
                              'ituverava',
                           'miguelopolis',
                                'aramina',
                           'miguelópolis',
                              'buritizal',
                                  'guara',
                                  'guará',
           'sao benedito da cachoeirinha',
                              'pioneiros',
                                   'ipua',
                   'sao joaquim da barra',
                            'morro agudo',
                               'orlandia',
                           'jardinopolis',
                               'orlândia',
                   'são joaquim da barra',
                           'jardinópolis',
                                   'ipuã',
                         'sales oliveira',
                              'nuporanga',
                                 'jurucê',
                                 'juruce',
                               'barretos',
                              'bebedouro',
                              'viradouro',
                                 'guaira',
                               'colombia',
                                 'taiúva',
                           'pitangueiras',
                                 'guaíra',
                    'monte azul paulista',
                                 'colina',
                              'severinia',
                                 'taiacu',
                             'terra roxa',
                                 'taiuva',
                               'ibitiuva',
                              'jaborandi',
                              'severínia',
                               'taquaral',
                               'colômbia',
                                 'taiaçu',
                             'araraquara',
                         'gaviao peixoto',
                            'jaboticabal',
                            'santa lucia',
                               'barrinha',
                                  'ibaté',
                    'americo brasiliense',
                                 'rincao',
                                'guariba',
                                  'ibate',
                             'pradopolis',
                    'américo brasiliense',
                             'pradópolis',
                                 'rincão',
                                 'motuca',
                         'gavião peixoto',
                            'santa lúcia',
                               'ibitinga',
                               'itapolis',
                         'novo horizonte',
                              'tabatinga',
                            'nova europa',
                                 'irapua',
                           'nova america',
                               'itápolis',
                              'borborema',
                   'boa esperanca do sul',
                                  'sales',
                   'boa esperança do sul',
                                'trabiju',
                                 'irapuã',
                                'tapinas',
                                 'curupa',
                           'nova américa',
                  'sao jose do rio preto',
                  'são josé do rio preto',
                               'mirassol',
                        'monte aprazível',
                                 'tanabi',
                         'neves paulista',
                                   'jaci',
                           'bady bassitt',
                 'sebastianopolis do sul',
                               'guapiacu',
                              'nhandeara',
                                'bálsamo',
                            'potirendaba',
                               'guapiaçu',
                        'monte aprazivel',
                                 'poloni',
                                'balsamo',
                          'mirassolandia',
                                 'ipigua',
                    'engenheiro balduíno',
                                 'ipiguá',
                    'engenheiro balduino',
                 'sebastianópolis do sul',
                          'mirassolândia',

In [34]:
geolocation_df.geolocation_state.unique()

<StringArray>
['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB', 'CE', 'PI',
 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO', 'MT', 'MS', 'RS', 'PR',
 'SC']
Length: 27, dtype: str

In [35]:
geolocation_df.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [36]:
orders_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [37]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [38]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [39]:
columns_to_datetime = ("order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date")
for each in columns_to_datetime:
    orders_df[each] =  pd.to_datetime(orders_df[each])

In [40]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [41]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [42]:
orders_df.head(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04

In [43]:
orders_df.groupby("order_status")["order_delivered_customer_date"]

In [44]:
orders_df.groupby("order_status")[
    "order_delivered_customer_date"
].apply(lambda x: x.isnull().sum())

order_status
approved          2
canceled        619
created           5
delivered         8
invoiced        314
processing      301
shipped        1107
unavailable     609
Name: order_delivered_customer_date, dtype: int64

In [45]:
orders_df.loc[
    (orders_df["order_delivered_customer_date"].isna()) &
    (orders_df["order_status"] == "delivered")
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [46]:
orders_df.groupby("order_status")["order_delivered_customer_date"].count()

order_status
approved           0
canceled           6
created            0
delivered      96470
invoiced           0
processing         0
shipped            0
unavailable        0
Name: order_delivered_customer_date, dtype: int64

In [47]:
##now removing NaN from order_delivered_customer_date where 
# order_status is delivered

invalid_orders = orders_df.loc[
    (orders_df["order_status"] == "delivered") &
    (orders_df["order_delivered_customer_date"].isna())
].copy()

clean_orders = orders_df.loc[
    ~(
        (orders_df["order_status"] == "delivered") &
        (orders_df["order_delivered_customer_date"].isna())
    )
].copy()

In [48]:
invalid_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [49]:
print(orders_df.order_status.unique())

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [50]:
order_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [51]:
order_items_df.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [52]:
column_to_datetime = "shipping_limit_date"
order_items_df[column_to_datetime] = pd.to_datetime(order_items_df[column_to_datetime])

In [53]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [54]:
print(order_items_df.loc[
    order_items_df["price"]<0
])
print(order_items_df.loc[
    order_items_df["freight_value"]<0
])

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []
Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [55]:
order_payments_df.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [56]:
order_payments_df.head(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

In [57]:
order_payments_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [58]:
order_payments_df["payment_type"].unique()

<StringArray>
['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
Length: 5, dtype: str

In [59]:
order_payments_df.head(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

In [60]:
order_payments_df.loc[
    order_payments_df["payment_installments"]<0
]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [61]:
order_payments_df.loc[
    order_payments_df["payment_value"]<0
]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [62]:
order_reviews_df.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [63]:
columns_to_datetime= ("review_creation_date", "review_answer_timestamp")
for each in columns_to_datetime:
    order_reviews_df[each]= pd.to_datetime(order_reviews_df[each])

In [64]:
order_reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

In [65]:
order_reviews_df.head(2)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13

In [66]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [67]:
products_df.rename(columns={"product_name_lenght": "product_name_length"}, inplace=True)
products_df.rename(columns={"product_description_lenght":"product_description_length"}, inplace=True)

In [68]:
products_df.head()

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [79]:
(products_df["product_length_cm"] % 1 != 0).any()

np.True_

In [80]:
order_reviews_df["review_score"].unique()

array([4, 5, 1, 3, 2])

In [69]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_length         32341 non-null  float64
 3   product_description_length  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [70]:
products_df[
    products_df["product_category_name"].isna()
]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [71]:
sellers_df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [72]:
sellers_df.info(())

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [73]:
sellers_df.head(2)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

In [74]:
sellers_df.seller_state.unique()

<StringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [75]:
sellers_df.seller_city.unique()

<StringArray>
[                                'campinas',
                               'mogi guacu',
                           'rio de janeiro',
                                'sao paulo',
                        'braganca paulista',
                                   'brejao',
                                'penapolis',
                                 'curitiba',
                                 'anapolis',
                                'itirapina',
                                  'tubarao',
                         'lauro de freitas',
                                 'imbituba',
                                 'brasilia',
                             'porto seguro',
                                  'guaruja',
                                'tabatinga',
                                    'salto',
                             'tres de maio',
                           'belo horizonte',
                                'arapongas',
                    'sao bernardo do campo',
                                    'tatui',
                                 'garopaba',
                              'camanducaia',
                                     'tupa',
                                'guarulhos',
                     'sao jose dos pinhais',
                              'sao ludgero',
                                 'sao jose',
                               'piracicaba',
                             'porto alegre',
                                'congonhal',
                              'santo andre',
                                   'osasco',
                                 'valinhos',
                                'joinville',
                                'saquarema',
                              'barra velha',
                               'petropolis',
                'santo antonio da patrulha',
                             'ponta grossa',
                      'santana de parnaiba',
                               'sao carlos',
                                 'ibitinga',
                                  'barueri',
                            'caxias do sul',
                                 'araguari',
                                 'contagem',
                           'jaragua do sul',
                               'lages - sc',
                          'bento goncalves',
                                'catanduva',
                           'ribeirao pires',
                              'jaboticabal',
                                 'echapora',
                                    'cotia',
                               'rio do sul',
                                 'sorocaba',
                               'pradopolis',
                                 'itaborai',
                                 'mirassol',
                                  'birigui',
                                    'assis',
                               'jaguariuna',
                               'araraquara',
                                    'macae',
                                'rio claro',
                                 'londrina',
                           'ribeirao preto',
                            'tres coracoes',
                                'nhandeara',
                                  'orleans',
                                   'cuiaba',
                         'formosa do oeste',
                                   'santos',
                 'santa terezinha de goias',
                              'arvorezinha',
                                'guiricema',
                                  'caruaru',
                                   'franca',
                                 'salvador',
                                  'diadema',
                          'itaquaquecetuba',
                         'lencois paulista',
                              'carapicuiba',
                                   'uruacu',
                                   'itajai',
                                   'loanda',
                                  'maringa',
                    'ferraz de vasconcelos',
                                  'limeira',
                                  'claudio',
                                  'niteroi',
                             'osvaldo cruz',
                              'sao goncalo',
                                  'jaciara',
                       'balenario camboriu',
                                    'timbo',
                                'jacutinga',
                                'fortaleza',
                   'ferraz de  vasconcelos',
                             'mirandopolis',
                                    'bauru',
                                  'jacarei',
                                      'itu',
                       'laranjeiras do sul',
                                  'videira',
                            'florianopolis',
                     'itapecerica da serra',
                               'mamanguape',
                               'ponte nova',
                                  'goioere',
                              'pederneiras',
                                  'itapevi',
                                  'goiania',
                           'campina grande',
                           'estancia velha',
                                  'resende',
                                     'maua',
                                'caratinga',
                             'auriflama/sp',
                               'cafelandia',
                                      'uba',
                    'sao paulo / sao paulo',
                    'sao jose do rio preto',
                           'porto ferreira',
                              'tres coroas',
                                 'blumenau',
                          'mogi das cruzes',
                                     'jaci',
                        'laranjal paulista',
                                'americana',
                             'sertanopolis',
                                'apucarana',
                                  'colombo',
                      'vicente de carvalho',
                                 'mesquita',
                                 'sao pauo',
                                 'cascavel',
                       'fazenda rio grande',
                          'taboao da serra',
                      'sao jose dos campos',
                                   'toledo',
                  'marechal candido rondon',
                                  'jundiai',
                              'mandirituba',
                                   'suzano',
                               'vespasiano',
                               'santa rosa',
                     'sao joaquim da barra',
                   'santo antonio de posse',
                               'uruguaiana',
                                 'campanha',
                              'piracanjuba',
                                'concordia',
                    'santa rita do sapucai',
                                 'barretos',
                               'indaiatuba',
                                'nilopolis',
                                  'pompeia',
                               'barro alto',
                               'são paulo',
                             'praia grande',
                               'luiz alves',
                                  'brusque',
                                 'criciuma',
                                    'jales',
                                  'atibaia',
                               'rio branco',
                              'barra mansa',
                                  'marilia',
                                    'bahia',
                                  'taubate',
                                'cascavael',
                          'monteiro lobato',
                                    'viana',
                           'paraiba do sul',
                                   'mococa',
                                'sao roque',
                                   'passos',
                        'francisco beltrao',
                                'tocantins',
                               'porto belo',
                              'nova iguacu',
                                    'icara',
                                  'lajeado',
                              'horizontina',
                               'votorantim',
                                'campo bom',
                               'monte alto',
                            'fernandopolis',
                                 'pedreira',
                                      'poa',
                              'divinopolis',
                    'santa barbara d´oeste',
                                   'canoas',
                                  'mombuca',
                              'sete lagoas',
                            'campo do meio',
                            'cordeiropolis',
                               'uberlandia',
                    'santa barbara d oeste',
                            'volta redonda',
                                 '04482255',
                                'aracatuba',
                               'monte siao',
                                   'garuva',
                    'bonfinopolis de minas',
                               'cosmopolis',
                          'pocos de caldas',
                           'artur nogueira',
                              'joao pessoa',
                            'dois corregos',
                                 'araquari',
 'novo hamburgo, rio grande do sul, brasil',
                             'floranopolis',
                                   'sumare',
                                   'guaira',
                  'cachoeiro de itapemirim',
                                  'serrana',
                                 'rolandia',
                                'congonhas',
                    'sao  jose dos pinhais',
                                  'boituva',
                                'mairipora',
                                  'guaimbe',
                                    'parai',
                                  'aperibe',
                                'jaguaruna',
                               'vila velha',
                             'juiz de fora',
                                'fronteira',
                           'novo horizonte',
                             'pilar do sul',
                                  'itajobi',
                           'cariacica / es',
                                   'prados',
                                  'mucambo',
                            'montes claros',
                                   'vicosa',
                              'porto velho',
                    'sao jose do rio pardo',
                              'pato branco',
                         'sao joao del rei',
                      'presidente prudente',
                                'paracambi',
                              'serra negra',
                       'sao caetano do sul',
                               'bom jardim',
                            'serra redonda',
                     'sao francisco do sul',
                                    'betim',
                                 'imbituva',
                                'guaratuba',
                                 'teresina',
                       'sao miguel d'oeste',
                               'california',
                                   'japira',
                            'foz do iguacu',
                            'nova friburgo',
                            'itau de minas',
                                 'oliveira',
                                   'sabara',
                       'pedrinhas paulista',
                              'votuporanga',
                                 'holambra',
                                'ararangua',
                                  'pinhais',
                             'pato bragado',
                                'carazinho',
                                   'arinos',
                                'sao pedro',
                                    'lages',
                                   'ampere',
                                   'itauna',
                               'mogi mirim',
                              'curitibanos',
                              'brasilia df',
                          'mogi das cruses',
                              'hortolandia',
                                 'ipatinga',
                                   'laguna',
                          'dores de campos',
                           'sao paulo - sp',
                                   'araras',
                              'divisa nova',
                         'igaracu do tiete',
                             'pitangueiras',
                             'campo grande',
                                    'garca',
                      'presidente epitacio',
                                   'sbc/sp',
           'arraial d'ajuda (porto seguro)',
                                 'pacatuba',
                                  'formosa',
                            'borda da mata',
                                  'ubatuba',
                      'entre rios do oeste',
                                  'formiga',
                           'venancio aires',
                               'navegantes',
                                 'cruzeiro',
                              'santa maria',
                                   'muriae',
                    'santo andre/sao paulo',
                                      'ipe',
                          'messias targino',
                                 'varginha',
                                 'botucatu',
                         'domingos martins',
                                  'uberaba',
                       'coronel fabriciano',
                             'cachoeirinha',
                      's jose do rio preto',
                                   'taruma',
                             'pirassununga',
                                    'aruja',
                                  'sp / sp',
                           'angra dos reis',
                         'juzeiro do norte',
                               'laurentino',
                          'flores da cunha',
                               'montenegro',
                               'pedregulho',
                            'novo hamburgo',
                                   'torres',
                                  'aracaju',
                           'santa catarina',
                            'joao pinheiro',
                             'bady bassitt',
                                    'sinop',
                               'guarapuava',
                                'araucaria',
                                  'vitoria',
                                 'batatais',
                              'lagoa santa',
                                  'chapeco',
                                 'umuarama',
                             'belford roxo',
                                'cariacica',
                      'monte alegre do sul',
                                       'sp',
                           'lagoa da prata',
                                  'rolante',
                              'teresopolis',
                               'itaporanga',
                              'campo largo',
                       'sao joao de meriti',
                           'maua/sao paulo',
                    'bom jesus dos perdoes',
                                   'brotas',
                                    'irece',
                                    'coxim',
                                      'jau',
                     'conselheiro lafaiete',
                                   'amparo',
                      'sao miguel do oeste',
                                   'gaspar',
                               'rio bonito',
                               'mandaguari',
                   'vargem grande paulista',
                                  'conchal',
                                    'cambe',
                                 'marialva',
                                  'alfenas',
                       'balneario camboriu',
                                  'palhoca',
                     'sao bernardo do capo',
                                    'guara',
                                 'colatina',
                          'franco da rocha',
                                  'lambari',
                     'mogi das cruzes / sp',
                             'treze tilias',
           'rio de janeiro \rio de janeiro',
                              'paulo lopes',
                            'santa cecilia',
                           'braco do norte',
                                 'floresta',
                              'farroupilha',
                                   'castro',
                                 'luziania',
                           'joao monlevade',
                                  'pelotas',
                                'sao bento',
                    'campos dos goytacazes',
                                'ouro fino',
                      'sao jose dos pinhas',
                                    'tiete',
                                   'viamao',
                                  'janauba',
                                 'capivari',
                'santa terezinha de itaipu',
                                'igrejinha',
                         'sao bento do sul',
                          'duque de caxias',
                                    'araxa',
                                'canoinhas',
                                   'recife',
                  'barbacena/ minas gerais',
                                'vera cruz',
                               'parnamirim',
                             'santo angelo',
                                'paincandu',
                                'tres rios',
                                   'tanabi',
                            'portoferreira',
                                  'itatiba',
                                  'sarandi',
                                'cravinhos',
                                'morrinhos',
                                'bebedouro',
                      'almirante tamandare',
                                 'bertioga',
                                    'natal',
                            'belo horizont',
                                    'ivoti',
                                'andira-pr',
                          'cerqueira cesar',
                                'marapoama',
                                'imigrante',
                                'mairinque',
                             'sao paulo sp',
          'rio de janeiro / rio de janeiro',
                                 'andradas',
                              'sando andre',
                              'nova odessa',
                                 'paulinia',
                                  'extrema',
                                  'olimpia',
                        'angra dos reis rj',
                               'ronda alta',
                               'sao  paulo',
                              'sao vicente',
                               'pinhais/pr',
                                   'portao',
                                 'registro',
                     'ao bernardo do campo',
                          'carmo do cajuru',
                           'embu das artes',
                         'fernando prestes',
                             'castro pires',
                     'vargem grande do sul',

In [76]:
category_name_translation_df.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [77]:
category_name_translation_df.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [78]:
category_name_translation_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB